---
- hosts: elkstack
  roles:
    - role: ansible-change-hostname
    - role: ansible-etc-hosts
    - role: ansible-ntp
    - role: ansible-timezone
    - role: ansible-rsyslog

- hosts: brokers
  roles:
    - role: ansible-rabbitmq
      when: brokers_use_rabbitmq
    - role: ansible-redis
      when: brokers_use_redis

- hosts: pre_processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-pre-processor

- hosts: processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-processor

- hosts: elasticsearch
  roles:
    - role: ansible-elasticsearch

- hosts: dashboard
  roles:
    - role: ansible-grafana
    - role: ansible-kibana

- hosts: loadbalancers
  roles:
    - role: ansible-keepalived
    - role: ansible-haproxy
