---
- hosts: all
  roles:
    - role: ansible-change-hostname
    - role: ansible-etc-hosts
    - role: ansible-ntp
    - role: ansible-timezone
    - role: ansible-rsyslog

# - hosts: redis
#   roles:
#     - role: ansible-redis

- hosts: rabbitmq
  roles:
    - role: ansible-rabbitmq

- hosts: pre_processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-pre-processor

- hosts: processors
  roles:
    - role: ansible-dnsmasq
    - role: ansible-logstash
    - role: ansible-elk-processor

- hosts: elasticsearch
  roles:
    - role: ansible-elasticsearch

- hosts: grafana
  roles:
    - role: ansible-grafana

- hosts: kibana
  roles:
    - role: ansible-kibana

- hosts: loadbalancers
  roles:
    - role: ansible-keepalived
    - role: ansible-haproxy
