---
- src: https://github.com/mrlesmithjr/ansible-apache2
- src: https://github.com/mrlesmithjr/ansible-dnsmasq
- src: https://github.com/mrlesmithjr/ansible-elasticsearch
- src: https://github.com/mrlesmithjr/ansible-elk-kibana
- src: https://github.com/mrlesmithjr/ansible-es-filebeat
- src: https://github.com/mrlesmithjr/ansible-es-packetbeat
- src: https://github.com/mrlesmithjr/ansible-es-topbeat
- src: https://github.com/mrlesmithjr/ansible-logstash
- src: https://github.com/mrlesmithjr/ansible-mariadb-mysql
- src: https://github.com/mrlesmithjr/ansible-ntp
- src: https://github.com/mrlesmithjr/ansible-redis
- src: https://github.com/mrlesmithjr/ansible-rsyslog
- src: https://github.com/mrlesmithjr/ansible-timezone
