---
es_allow_remote_connections: true
#es_plugin_install: -i  #define when ES vversion is below 2.x
es_plugin_install: install  #define when ES version is 2.x+
#es_plugin_list: -l  #define when ES version is below 2.x
es_plugin_list: list  #define when ES version is 2.x+
es_replicas: 1
es_shards: 5
es_version: 2.x
kibana_version: 4.5.1
logstash_config_dir: /etc/logstash/conf.d
logstash_configs:
  - 000_inputs
  - 001_filters
  - 200_filters_syslog
  - 999_outputs
logstash_inputs:
  - prot: beats
    port: 5044
    type: beats
  - prot: tcp
    port: 10514
    type: syslog
  - prot: tcp
    port: 1514
    type: VMware
  - prot: tcp
    port: 1515
    type: vCenter
  - prot: tcp
    port: 1517
    type: Netscaler
  - prot: tcp
    port: 28778
    type: elasticsearch-curator
  - prot: tcp
    codec: json
    port: 3515
    type: eventlog
  - prot: tcp
    codec: json_lines
    port: 3525
    type: iis
  - prot: tcp
    codec: json
    port: '{{ rundeck_logstash_port }}'
    type: rundeck
logstash_outputs:
  - output: elasticsearch
    hosts: '{{ logstash_server_fqdn }}:9200'
    protocol: http  #node, transport or http....http is the only protocol supported in 2.x+
    flush_size: 5000
    workers: 2
logstash_server_fqdn: 127.0.0.1
logstash_version: 2.3
rundeck_logstash_port: 9700
