---
- name: kibana | creating kibana service account
  user:
    name: kibana
    system: yes
    home: /var/lib/kibana
    shell: /bin/false
    state: present

- name: kibana | downloading kibana
  get_url:
    url: "{{ kibana_dl_url }}/{{ kibana_dl_file }}.tar.gz"
    dest: "{{ kibana_dl_dir }}/{{ kibana_dl_file }}.tar.gz"

- name: kibana | extracting and installing kibana
  unarchive:
    src: "{{ kibana_dl_dir }}/{{ kibana_dl_file }}.tar.gz"
    dest: "{{ kibana_dir }}"
    copy: no
    creates: "{{ kibana_dir }}/{{ kibana_dl_file }}"
    owner: kibana
    group: kibana

- name: kibana | checking for babelcache
  stat:
    path: "{{ kibana_dir }}/{{ kibana_dl_file }}/optimize/.babelcache.json"
  register: babelcache_check
  when: kibana_fix_babelcache_perms

- name: kibana | setting permissions on babelcache
  file:
    path: "{{ kibana_dir }}/{{ kibana_dl_file }}/optimize/.babelcache.json"
    owner: kibana
    group: kibana
    mode: o+w
  when: >
        kibana_fix_babelcache_perms and
        babelcache_check.stat.exists

- name: kibana | set babelcache permissions
  file:
    path: "{{ kibana_dir }}/{{ kibana_dl_file }}/optimize/.babelcache.json"
    state: touch
    owner: kibana
    group: kibana
    mode: o+w
  when: >
        kibana_fix_babelcache_perms and
        not babelcache_check.stat.exists

- name: kibana | configuring kibana
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_dir }}/{{ kibana_dl_file }}/config/kibana.yml"
  notify: restart kibana

- name: kibana | checking for existing kibana log file
  stat:
    path: "{{ kibana_log }}"
  register: kibana_log_file

- name: kibana | creating kibana log file
  file:
    path: "{{ kibana_log }}"
    state: touch
    owner: kibana
    group: kibana
    mode: 0644
  when: not kibana_log_file.stat.exists

- name: kibana | configure kibana log rotation
  template:
    src: etc/logrotate.d/kibana.j2
    dest: /etc/logrotate.d/kibana
    owner: root
    group: root
    mode: 0644

- name: kibana | configuring Docker startup script
  template:
    src: kibana.sh.j2
    dest: /opt/kibana.sh
    owner: root
    group: root
    mode: 0744
  when: kibana_docker_install is defined and kibana_docker_install
